### ISSUE TITLE
Module for THT

### ISSUE THREAD

**Issue by Dylan3304** [PufferPanel/PufferPanel#464] opened 2015-03-14 03:54 UTC
Hi all,
I've got a big favor to ask upon the developers of PufferPanel, on behalf of the community. When the API is finished in 0.8.0, I ask the team to write a provisioning module for [THT](https://thehostingtool.com). This would allow hosting providers to charge even cheaper prices for not having to pay for a control panel or billing system. The module should include:
* Automatic account/server creation for new clients.
* Multiple servers for one account.
* Custom plans, etc.
* Anything else you think would be useful.
I would write this myself but I don't have time or the skills necessary.

Let me know what you think,
Dylan3304.

**Comment by Dylan3304** [comment] 2015-03-14 04:27
After doing more research, THT isn't a sutable platform to work with. I much rather see a BoxBilling extension.

**Comment by Wargog** [comment] 2015-03-14 13:55
It doesn't matter what type of billing platform you use, it would still integrate with the API in almost the same way. So ideally you would have your choice of what kind of billing panel to use.

**Comment by Dylan3304** [comment] 2015-03-14 14:50
@Wargog could you be more specific?

**Comment by Wargog** [comment] 2015-03-14 14:55
When the API is finished, the functions to interact with the panel are going to be the same no matter what billing panel you use. So if someone makes a plugin for billing panels it should work with any billing panel.

**Comment by Dylan3304** [comment] 2015-03-14 15:55
So there will be one universal billing system plugin? @Wargog

**Comment by worldmc** [comment] 2015-03-14 16:18
No, it all depends on what the creator makes in that plugin. 

The api functions that pufferpanel is going to have will be the smae for each and all. however, each billing software could handle things different. Saying that its universal doesnt count. You would still need a plugin to bind the api and the billing panel thogether. 

(hope i gave a good enough explonation)

**Comment by Dylan3304** [comment] 2015-03-14 19:28
That makes sense, @worldmc. I hope someone makes a BoxBilling module.

**Comment by puffrfish** [comment] 2015-03-15 06:01
Based upon previous discussions on the topic of billing software modules, I don't think we have any current commitment to making our own billing modules. Of course, anyone can use the API to make a module for whatever software they please, but as far as modules supported by the project I believe we are going to stick to developing the best API for them as we can. We will continue to monitor community feedback, but modules can only be written after the API is finished.

I believe I can speak for the PufferPanel team when I say that we care deeply about security, especially when it comes to billing information. Please choose wisely when selecting a billing software and treat your clients' billing information with care. Any community members working on modules are highly encouraged to keep security in mind.

Closing this issue as it's pretty much a duplicate of previous requests for other billing software modules.

**Closed by puffrfish** 2015-03-15 06:01 UTC
