### ISSUE TITLE
Console Refresh Problem

### ISSUE THREAD

**Issue by joshua242** [PufferPanel/PufferPanel#418] opened 2015-01-27 13:53 UTC
Hey when I click start on a non local machine it says server starting and then does nothing until u refresh and then when u run a command, pause, restart or stop server it displays this error: We were unable to connect to the main server, there may be network issues currently. This message will disappear when we are able to connect, you do not need to refresh. Also this error log src/logs/exception.log doesnt exist. I am using http:// not https://. If you have skype I would be happy to add you for a quicker solution. Thanks Joshua

Specs:

GSD 0.1.4
PufferPanel: 0.7.6
OS: Ubuntu
Web: Apache2

**Comment by DaneEveritt** [comment] 2015-01-27 16:50
Check your firewall, both on the remote machine and your local one.

**Comment by joshua242** [comment] 2015-01-27 17:06
My firewall is disabled and Ipad and another Ubuntu machine was tried by still same error. Also GSD is online

**Comment by joshua242** [comment] 2015-01-27 17:07
You dont have skype by any chance do u?

**Comment by DaneEveritt** [comment] 2015-01-27 17:18
That connection error is indicative of a network issue since it cannot connect to GSD correctly. Does the server actually start correctly when you press the start button, or does nothing happen?

**Comment by joshua242** [comment] 2015-01-27 17:20
When you click start it says server starting... then console display freezes but when u refresh server has started and u have to refresh to get updated console.

**Comment by DaneEveritt** [comment] 2015-01-27 17:50
Can you open the developer pane in your browser (can often right click, view source or view developer; otherwise check the menu) and see if any javascript errors are being thrown?

On Safari it is [Right Click] --> Developer Pane, should be very similar on Chrome or Firefox. When you do that, there is a box similar to [this](http://s3.kelp.in/8d3rt.png) that pops up. Click where that red ! is, and then either copy and paste, or take a picture of [what shows up](http://s3.kelp.in/MgPr6.png).

**Comment by joshua242** [comment] 2015-01-27 17:58
It cant be an error like that since it works on local but not through internet

**Comment by joshua242** [comment] 2015-01-27 18:01
my friend is offline at the moment so that would be hard to do but if u have skype or something i could send login details to that would be good.

**Comment by joshua242** [comment] 2015-01-27 18:25
do u have skype an email or something

**Comment by joshua242** [comment] 2015-01-27 19:10
i need an email or something so i can send u login details to my panel on my website since my friend is offline.

**Comment by DaneEveritt** [comment] 2015-01-27 21:39
Until you provide the errors that I requested I, nor anyone else, can help you fix it. I find it incredibly hard to believe that this issue is being caused by something other than a configuration issue on your end since the panel works fine on many other environments.

Please stop acting like a child posting constantly trying to get help and *please* stop asking for Skype support. I'm not your personal developer that you can get to fix everything. This is free, **beta**, software that probably has some things that don't work, but you have provided nothing that is of any help to us for debugging purposes.

**Comment by joshua242** [comment] 2015-01-27 21:45
I am sorry as i said my friend is offline and I came up with an alternate solution I give you login details to my panel on my website but to do so I need someone of sending it to you privately.

**Comment by DaneEveritt** [comment] 2015-01-27 21:48
The steps I outlined above do not require you to do anything other than be able to login to the panel.

**Comment by joshua242** [comment] 2015-01-27 21:50
but it would help running of local machine as i dont get the error on an local machine only non local

**Comment by DaneEveritt** [comment] 2015-01-27 21:52
Then you will need to find a way to connect to it through a non-local machine and report back with your findings.

**Comment by Optigonnn** [comment] 2015-01-27 22:17
Use google chrome, firefox is messed up.

**Comment by CptTr0ller** [comment] 2015-01-27 22:22
sorry just wake up in this morning
"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://192.168.1.104:8031/socket.io/?token=2b283178-dd38-4503-9de4-3f90c8291484&EIO=2&transport=polling&t=1422397056868-0. This can be fixed by moving the resource to the same domain or enabling CORS."
Is that what you want?
I imagine what the problem is....

**Comment by joshua242** [comment] 2015-01-27 22:24
there u go DaneEveritt hope thats what u wanted

**Comment by DaneEveritt** [comment] 2015-01-27 22:55
Disable HTTPS.

**Comment by joshua242** [comment] 2015-01-27 22:55
how?

**Comment by CptTr0ller** [comment] 2015-01-27 22:56
>Disable HTTPS.
>HTTPS already disabled before you said that
Top lel

**Comment by joshua242** [comment] 2015-01-27 23:09
DaneEveritt how do I disable https

**Comment by DaneEveritt** [comment] 2015-01-28 03:59
First: why are you connecting to local IP address through a remotely accessible web panel. That is always going to fail unless you are on the same network as the "remote" machine.

Secondly: What browser are you using?

**Comment by joshua242** [comment] 2015-01-28 04:00
why did u say Disable HTTPS.

**Comment by DaneEveritt** [comment] 2015-01-28 04:02
What is the URL you use to access your panel?

**Comment by joshua242** [comment] 2015-01-28 04:03
http://panel.cosmorealm.net

**Comment by DaneEveritt** [comment] 2015-01-28 04:07
You do realize that is Multicraft... right?

**Closed by DaneEveritt** 2015-01-28 04:07 UTC
Labels: investigating

**Comment by joshua242** [comment] 2015-01-28 04:08
check again

**Comment by joshua242** [comment] 2015-01-28 04:10
I changed it back to PufferPanel

**Comment by joshua242** [comment] 2015-01-28 04:10
sorry was testing something

**Comment by DaneEveritt** [comment] 2015-01-28 04:11
What browser are you using, and for the love of god, please stop making a bunch of short replies, hit the edit button.

**Comment by joshua242** [comment] 2015-01-28 04:12
Google Chrome

**Comment by DaneEveritt** [comment] 2015-01-28 04:13
I have no idea what could be causing it then. Haven't had anyone else encounter this issue, and if they do it is because they are using a secure connection which is a known bug.

**Comment by joshua242** [comment] 2015-01-28 04:17
so what should I do now?

**Comment by joshua242** [comment] 2015-01-28 04:18
If it satifiys you I can give u login detail and see if you come up with anything else?

**Comment by c0urier** [comment] 2015-02-12 13:33
I have the same issues on Debian.

I can start the server, nothing happens until I refresh. The server is running, but i'll keep getting the error message:
We were unable to connect to the main server, there may be network issues currently. This message will disappear when we are able to connect, you do not need to refresh.

The server is running, but start,stop,restart,kill it, statistics are not working and will give the error mentioned above. If I kill the server, I am able to start it again once, and that's it.

**Comment by DaneEveritt** [comment] 2015-02-12 17:20
Are you running with HTTPS?

If yes, disable it and try again. Make sure you are not on a secure page when checking if it is working, there is a known issue with browsers blocking connections to GSD when running on a secure connection.

If you are not using a secure connection:

1.) SSH into the machine running PufferPanel
2.) Send a ping request to the machine running GSD, on port 8031 and 8003. Make sure connections can be recieved. If they can, let me know, if not, it is a firewall issue.

**Comment by c0urier** [comment] 2015-02-12 20:37
@DaneEveritt Thanks for the reply.

I have fixed the issues, it was purely my mistake. I have two IPs on the node, one internal and one external, the internal was listed first, causing the panel not being able to refresh for remote clients. I switched the IP's around so that the external was primary and it started updating as expected. Sorry for the trouble.

**Comment by joshua242** [comment] 2015-02-15 01:23
Hey c0urier I think you have the fix for my problem but i dont understand what you mean by switch the interanal and external ips around. Please explain more. Thanks Joshua

**Comment by c0urier** [comment] 2015-02-15 01:28
Could you post a screenshot of your node -> Allocation (IP & Port Allocation), and I can tell if it's the same problem.

**Comment by joshua242** [comment] 2015-02-15 01:35
There you go thanks for helping me out
![bandicam 2015-02-15 14-34-04-864](https://cloud.githubusercontent.com/assets/10725830/6201740/ca5b7d10-b51f-11e4-928a-92f378117998.jpg)

**Comment by c0urier** [comment] 2015-02-15 01:37
Okay, I switched those two IP's around in the DB, and it started working.

It can easily be done through phpmyadmin.

**Comment by joshua242** [comment] 2015-02-15 01:52
nah it didnt fix it

**Comment by c0urier** [comment] 2015-02-15 01:58
Fair, else drop a screenshot of your table

**Comment by joshua242** [comment] 2015-02-15 02:00
I tryed creating new node and server just in case but when i create server im getting error: Undefined index: id

**Comment by c0urier** [comment] 2015-02-15 02:05
If you recreated the node with the IPs in correct order, then our issues were not alike unfortunately.

**Comment by joshua242** [comment] 2015-02-15 02:06
how would i fix Undefined index: id

**Comment by DaneEveritt** [comment] 2015-02-15 02:53
The order of the IPs has no effect. You need to set servers to run on an IP that GSD can access. That is generally 127.0.0.1 or a public facing IP.

Additionally, this issue is unrelated to that IP issue, but it rather a problem with the websocket, most likely due to HTTPS.

**Comment by joshua242** [comment] 2015-02-15 03:47
i dont use https
