### ISSUE TITLE
Scheduler

### ISSUE THREAD

**Issue by phlupp** [PufferPanel/PufferPanel#606] opened 2015-08-28 07:59 UTC
Nice to have a scheduler for timeing server commands.

I'am working on this option. Also Scales will be modified to suport the scheduler

**Comment by puffrfish** [comment] 2015-08-30 22:01
Duplicate of #474. Please keep in mind we are currently in a feature freeze for the PHP version of PufferPanel so we won't be able to include it in a release unless it is done on the kraken branch. Thanks!

**Closed by puffrfish** 2015-08-30 22:01 UTC
