### ISSUE TITLE
Cron

### ISSUE THREAD

**Issue by XInfiniterX** [PufferPanel/PufferPanel#665] opened 2016-01-21 19:36 UTC
Possible to add scheduled commands like auto restarts minecraft servers, send commands to server like /save-all

every x seconds x minutes x hours x days etc. like in cron

I need this for my servers.

Sorry for my English.

**Comment by xion87** [comment] 2016-01-26 12:33
+1 for this, also a auto-backup/restart function will be usefull with this

**Comment by puffrfish** [comment] 2016-01-27 14:54
Duplicate of #474

**Closed by puffrfish** 2016-01-27 14:54 UTC
