### ISSUE TITLE
Implementing a scheduler

### ISSUE THREAD

**Issue by aadeg** [PufferPanel/PufferPanel#551] opened 2015-06-07 17:26 UTC
I used to use Multicraft and the lack of a scheduler is unfortunately a negative point for PufferPanel. It is important for a user to have a way to have scheduled commands that will be run on one server whenever it's needed. 
If you can implement it in the future updates, PufferPanel will become a real competitor of the no-opensource server managers.

Thank you very much.

**Comment by puffrfish** [comment] 2015-06-07 17:27
I would also like to see this.
Duplicate of #474, closing.

**Closed by puffrfish** 2015-06-07 17:27 UTC
