### ISSUE TITLE
Scales shows offline with Self Signed Certificate

### ISSUE THREAD

**Issue by Blackbyte1604** [PufferPanel/PufferPanel#525] opened 2015-05-02 07:21 UTC

**Comment by puffrfish** [comment] 2015-05-02 08:16
Confirmed.

**Comment by puffrfish** [comment] 2015-05-02 08:21
Might be a duplicate of #515, but I'm keeping this one instead.

**Comment by Blackbyte1604** [comment] 2015-05-02 13:10
Is there a workaround for this bug?

**Comment by puffrfish** [comment] 2015-05-02 15:56
Not at this time. This issue is currently being investigated and will hold back release of 0.8.0 until it is fixed.

**Comment by Dylan3304** [comment] 2015-05-02 16:11
This solved it for me:
```
cd /etc/php5 | or where ever your PHP directory is stored.
curl -O http://curl.haxx.se/ca/cacert.pem
```
Then you need to edit your `php.ini` file, which is probably somewhere in /etc/php5 and add this to the file: curl.cainfo = "/etc/php5/cacert.pem". Restart php and apache after that.

**Comment by Blackbyte1604** [comment] 2015-05-02 16:23
This didnt fix it because i have an self signed certificate

**Comment by DaneEveritt** [comment] 2015-05-02 16:30
What errors are being logged into src/logs/info.log? Self signed certificates can be a bit problematic if filled out wrong. What is the FQDN you are using for the certificate?

**Comment by Blackbyte1604** [comment] 2015-05-02 16:35
What errors are being logged into src/logs/info.log?
- This file doesnt exist.
What is the FQDN you are using for the certificate?
- minecraft.teamblackbird.net

**Comment by DaneEveritt** [comment] 2015-05-02 20:31
`src/logs/info.log` should exist on the PufferPanel system, make sure that you `chmod 0777 src/logs` so that PHP can write to it.

**Comment by DaneEveritt** [comment] 2015-05-02 20:39
Ok, took a look at your certificate, and it will never be accepted no matter what we do because you did not properly create it. It looks like you just skipped filling out any of the fields that showed up during the process, which will not work.

You need to fill out all of the first fields (not the ones where they ask for a password and such). Especially important is the common name, which **MUST** match the DNS resolving to your server. For this, you need to enter `minecraft.teamblackbird.net`.

**Comment by DaneEveritt** [comment] 2015-05-03 01:52
Closing this until someone provides further proof that this is actually an issue and not the result of a misconfigured SSL certificate.

**Closed by DaneEveritt** 2015-05-03 01:52 UTC
Labels: bug, priority

**Comment by Blackbyte1604** [comment] 2015-05-03 08:32
Thats weird. I filled out everything it asked me, common name is minecraft.teamblackbird.net.

**Comment by Blackbyte1604** [comment] 2015-05-03 08:33
Ive followed the tutorial and entered the command but it didnt ask me a password?

**Comment by computerwizjared** [comment] 2015-05-03 11:55
An SSL certificate is per FQDN (or domain name). Do not enter the port when it asks about FQDNs, only the domain name.

**Comment by Blackbyte1604** [comment] 2015-05-03 12:30
I know. I just wanted to clearify where i use which Certificate.

**Comment by Dylan3304** [comment] 2015-05-03 17:10
Please paste the result of 'nano /etc/resolv.conf'.

**Comment by Blackbyte1604** [comment] 2015-05-03 17:35
@DaneEveritt  @puffrfish  can you pls reopen it?

Info.log:

[2015-05-02 18-19-50] Exception: SSL: certificate subject name 'minecraft.teamblackbird.net' does not match target host name '84.201.32.183' in /var/www/public_html/pufferpanel/vendor/mashape/unirest-php/src/Unirest/Request.php:427  @  https://minecraft.teamblackbird.net/admin/server/new  @@  exception-2015-05-02-18-19-50-6c8907b1478a8b5736e6658ae01e9522.html
@Dylan3304 
nameserver 8.8.8.8
nameserver 8.8.4.4

**Comment by DaneEveritt** [comment] 2015-05-03 21:12
`certificate subject name 'minecraft.teamblackbird.net' does not match target host name '84.201.32.183'`.

You are connecting to your server using `84.201.32.183`, and not the FQDN `minecraft.teamblackbird.net` so the certificate is being rejected.
