### ISSUE TITLE
CloudFlare Subdomain Integration

### ISSUE THREAD

**Issue by Dylan3304** [PufferPanel/PufferPanel#500] opened 2015-04-07 20:54 UTC
Many of you may have heard of CloudFlare, a DNS provider/website optimization service. You could enable creation of a subdomain record when a server is created. For example:

**Admin** = User that has administrative access to the server.
**Cloudflare API** = CloudFlare API, which can be found [here](https://www.cloudflare.com/docs/client-api.html#s1.1)
**PufferPanel API** = The soon to be released PufferPanel API.
**User** = A generic PufferPanel user/client.

**Flow:**
1. During installation, Admin has an option to use CloudFlare. He chooses yes, and specifies his Api key.
2. Admin then creates a server, and specifies a subdomain, or inputs one of the user's choice.
3. PufferPanel creates the server and creates the record on CloudFlare.
4. User logins in and doesn't like his/her subdomain. He/she can change it using the server management tab.

Admins should be able to disable this feature, and the PufferPanel API should support this for use in WHMCS, BoxBilling, etc.

I might submit a pull request tonight...

Thank you!

**Comment by puffrfish** [comment] 2015-04-27 04:36
Related #456 #142

**Comment by DaneEveritt** [comment] 2015-04-28 17:58
Duplicate of #142.

**Closed by DaneEveritt** 2015-04-28 17:58 UTC
