### ISSUE TITLE
Some erros while uploading / creating new files

### ISSUE THREAD

**Issue by G1nux** [PufferPanel/PufferPanel#398] opened 2015-01-04 17:22 UTC
GSD-Version: 0.1.4
PP-Version: 0.7.6.1-beta

Existing Files can be changed (edited) and saved without errors. 
"Internal Server Error" when creating a new file with the Plus-Button
"File could not be uploaded: unable to write file to server" when uploading a file
"Error occured trying to delete that file! Unable to login to the FTP server!" when I try to delete a file

**Comment by LordRalex** [comment] 2015-01-04 17:24
The write error sounds like incomplete or bad perms. 
Can you provide the gsd logs and panel error logs?

**Comment by G1nux** [comment] 2015-01-04 17:43
Okay, I think I got it...
Here is my GSD-Config.json: http://pastebin.com/Cm7mzGGz
As you can see, I changed the FTP-Port from 21 to 50002. I already run an FTP-Server on my server, that's why I have to change this.
Here's the Exception from PP (HTML): http://pastebin.com/4C4vu5Hf
Also an "info.log" was generated:  http://pastebin.com/MA42RdBb

**Comment by LordRalex** [comment] 2015-01-04 17:45
Yeah, the issue is the changed port, which we already were aware of. We hardcocded the port, but we will fix that in 0.8.0

**Comment by LordRalex** [comment] 2015-01-04 17:46
https://github.com/PufferPanel/PufferPanel/issues/377

**Comment by LordRalex** [comment] 2015-01-04 17:46
For upload, make sure src/cache is set to 777 (iirc).

**Comment by DaneEveritt** [comment] 2015-01-04 17:49
Yeah that error looks like it is being caused by the changed FTP port. You'd have to manually update those hardcoded ports to fix it.

**Comment by G1nux** [comment] 2015-01-04 17:52
Okay, I'll wait until 0.8.0 and see how it will work ;)

**Comment by LordRalex** [comment] 2015-01-04 17:53
I will close this then since the issue is already reported.

**Closed by LordRalex** 2015-01-04 17:53 UTC
